# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20190226_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationfield',
            name='formula_terms',
            field=models.ManyToManyField(blank=True, help_text=b"Fields used in this field's formula calculation.", related_name='calculated_fields', to='credits.DocumentationField'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
