PRELOADED_SUBSCRIPTION_NAMES = set()

for name in (
    "ALBA Graduate Business School at the American College of Greece",
    "Agnes Scott College",
    "Alaska Pacific University",
    "Alfred State College",
    "Allegheny College",
    "American University",
    "American University of Nigeria",
    "Amherst College",
    "Anne Arundel Community College",
    "Antioch University, Los Angeles",
    "Appalachian State University",
    "Aquinas College",
    "Arizona State University",
    "Art Center College of Design",
    "Auburn University",
    "Augustana College",
    "Babson College",
    "Ball State University",
    "Bard College",
    "Bastyr University",
    "Baylor University",
    "Bellevue College",
    "Belmont University",
    "Beloit College",
    "Bentley University",
    "Berea College",
    "Berklee College of Music",
    "Black Hills State University",
    "Boston College",
    "Boston University",
    "Bowdoin College",
    "Brandeis University",
    "BridgeValley Community and Technical College",
    "Bridgewater College",
    "Brunswick Community College",
    "Bryant University",
    "Bucknell University",
    "Butte College",
    "California State Polytechnic University, Pomona",
    "California State University, Channel Islands",
    "California State University, Chico",
    "California State University, Fullerton",
    "California State University, Long Beach",
    "California State University, Monterey Bay",
    "California State University, Sacramento",
    "Camosun College",
    "Carleton College",
    "Carleton University",
    "Carnegie Mellon University",
    "Cascadia College",
    "Case Western Reserve University",
    "Cedar Valley College - DCCCD",
    "Central Carolina Community College",
    "Central College",
    "Central New Mexico Community College",
    "Central Ohio Technical College",
    "Champlain Regional College, Lennoxville",
    "Chapman University",
    "Chatham University",
    "Chiba University",
    "Claremont McKenna College",
    "Clarion University of Pennsylvania",
    "Clarkson University",
    "Cleveland State University",
    "Coastal Carolina University",
    "Colby College",
    "Colgate University",
    "College of Charleston",
    "College of Lake County",
    "College of Menominee Nation",
    "College of Saint Benedict",
    "College of Southern Idaho",
    "Colorado College",
    "Colorado School of Mines",
    "Colorado State University",
    "Columbia University",
    "Concordia College-Moorhead",
    "Concordia University",
    "Cornell University",
    "Dalhousie University",
    "Danish Institute for Study Abroad",
    "Dartmouth College",
    "Davidson College",
    "De Anza College",
    "DePaul University",
    "DePauw University",
    "Delaware State University",
    "Delta College",
    "Denison University",
    "Dickinson College",
    "Doane College",
    "Dominican University of California",
    "Drew University",
    "Drexel University",
    "Duke University",
    "Dundalk Institute of Technology",
    "Durham College",
    "Earlham College",
    "East Carolina University",
    "East Tennessee State University",
    "Eastern Connecticut State University",
    "Eastern Iowa Community College District",
    "Eastern Mennonite University",
    "Eastern Oregon University",
    "Edison State College, Collier Campus",
    "Edmonds Community College",
    "Eindhoven University of Technology",
    "El Centro College - DCCCD",
    "Elizabethtown College",
    "Elon University",
    "Emory University",
    "Endicott College",
    "Estrella Mountain Community College",
    "Euromed Management",
    "Evergreen State College, The",
    "Fairfield University",
    "Fanshawe College",
    "Fayetteville State University",
    "Ferrum College",
    "Fleming College",
    "Florida Gulf Coast University",
    "Florida International University",
    "Florida State University",
    "Franklin & Marshall College",
    "Franklin University Switzerland",
    "Frostburg State University",
    "Furman University",
    "George Brown College",
    "George Mason University",
    "George Washington University",
    "Georgia College & State University",
    "Georgia Institute of Technology",
    "Gettysburg College",
    "Glasgow Caledonian University",
    "Golden West College",
    "Gonzaga University",
    "Gordon College",
    "Goshen College",
    "Grand Valley State University",
    "Green Mountain College",
    "Guilford College",
    "Hampshire College",
    "Hanover College",
    "Harrisburg Area Community College",
    "Hartwick College",
    "Haverford College",
    "Hawaii Pacific University",
    "Haywood Community College",
    "Hibbing Community College",
    "Hobart and William Smith Colleges",
    "Hofstra University",
    "Hokkaido University",
    "Hope College",
    "Hopkinsville Community College",
    "Humber College",
    "Humboldt State University",
    "ITESM",
    "Illinois Central College",
    "Illinois Institute of Technology",
    "Illinois State University",
    "Indiana State University",
    "Indiana University Bloomington",
    "Indiana University-Purdue University Indianapolis",
    "Instituto Tecnolgico y de Estudios Superiores de Monterrey",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Central de Veracruz",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Ciudad Obregon",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Ciudad de México",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Estado de México",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Guadalajara",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Hidalgo",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Irapuato",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Laguna",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Leon",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Monterrey",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Morelia",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Puebla",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Queretaro",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus San Luis Potosi",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Santa Catarina",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Santa Fe",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Sinaloa",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Sonora Norte",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Tampico",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey Campus Toluca",
    "Instituto Tecnologico y de Estudios Superiores de Monterrey System",
    "Iowa Lakes Community College",
    "Iowa State University",
    "Ithaca College",
    "Jackson Community College",
    "James Madison University",
    "Jefferson Community and Technical College",
    "John Abbott College",
    "John Brown University",
    "Johnson County Community College",
    "Joliet Junior College",
    "Jones County Junior College",
    "Judson University",
    "Kankakee Community College",
    "Kean University",
    "Keene State College",
    "Knox College",
    "Kyoto University",
    "LIU Post",
    "Lahore University of Management Sciences",
    "Lakehead University",
    "Lakeland Community College",
    "Lambton College of Applied Arts and Technology",
    "Lane Community College",
    "Lawrence University",
    "Lehigh University",
    "Les Roches Gruyere University of Applied Sciences Glion Institute of Higher Education",
    "Lethbridge College",
    "Lewis & Clark College",
    "Lipscomb University",
    "Lorain County Community College",
    "Los Angeles Community College District",
    "Louisiana State University",
    "Loyalist College",
    "Loyola Marymount University",
    "Loyola University Chicago",
    "Luther College",
    "Maastricht University",
    "MacEwan University",
    "Macalester College",
    "Madisonville Community College",
    "Maharishi University of Management",
    "Manhattan College",
    "Manhattanville College",
    "Marquette University",
    "Maryville College",
    "Massachusetts Institute of Technology",
    "McGill University",
    "McMaster University",
    "Miami University",
    "Michigan State University",
    "Middlebury College",
    "Mills College",
    "Minnesota State University Moorhead",
    "Missouri State University",
    "Missouri University of Science and Technology",
    "Mohawk College",
    "Moraine Valley Community College",
    "Morgan State University",
    "Mount Holyoke College",
    "Muhlenberg College",
    "Nanyang Technological University",
    "Naropa University",
    "New Mexico State University",
    "New York University",
    "Niagara College Canada",
    "North Carolina A&T State University",
    "North Carolina State University",
    "North Park University",
    "North Seattle College",
    "Northern Alberta Institute of Technology",
    "Northern Arizona University",
    "Northland College",
    "Northwest Missouri State University",
    "Northwestern University",
    "Nova Scotia Community College",
    "Oberlin College",
    "Ohio State University",
    "Ohio University",
    "Okanagan College",
    "Oklahoma City University",
    "Oklahoma State University",
    "Old Dominion University",
    "Olds College",
    "Onondaga Community College",
    "Orange County Community College",
    "Oregon Institute of Technology",
    "Oregon State University",
    "Pace University",
    "Pacific Lutheran University",
    "Pacific University",
    "Pennsylvania State University",
    "Pittsburg State University",
    "Pitzer College",
    "Point Loma Nazarene University",
    "Pomona College",
    "Portland Community College",
    "Portland State University",
    "Prescott College",
    "Princeton University",
    "Principia College",
    "Purdue University",
    "Queens University of Charlotte",
    "Ramapo College of New Jersey",
    "Raritan Valley Community College",
    "Red River College",
    "Rhode Island School of Design",
    "Rice University",
    "Richland College - DCCCD",
    "Richland Community College",
    "Ringling College of Art and Design",
    "Rio Salado College",
    "Rochester Institute of Technology",
    "Rocky Mountain College of Art + Design",
    "Roosevelt University",
    "Royal Roads University",
    "SUNY Adirondack",
    "Saint John's University",
    "Saint Joseph's College - ME",
    "Saint Louis University",
    "Saint Mary's College of California",
    "Saint Mary's University",
    "San Diego State University",
    "San Jose State University",
    "Santa Clara University",
    "Scripps College",
    "Seattle Central College",
    "Seattle Pacific University",
    "Seattle University",
    "Sewanee - The University of the South",
    "Sheridan Institute of Technology and Advanced Learning",
    "Shoreline Community College",
    "Simon Fraser University",
    "Skidmore College",
    "Slippery Rock University",
    "Smith College",
    "South Seattle College",
    "Southern Connecticut State University",
    "Southern Illinois University Carbondale",
    "Southern Illinois University Edwardsville",
    "Southern Methodist University",
    "Southern Oregon University",
    "Southwestern University",
    "St. Edward's University",
    "St. Lawrence College",
    "St. Lawrence University",
    "St. Mary's College of Maryland",
    "Stanford University",
    "Stark State College",
    "State University of New York College of Environmental Science and Forestry",
    "State University of New York at Brockport",
    "State University of New York at Cortland",
    "State University of New York at Fredonia",
    "State University of New York at Geneseo",
    "State University of New York at New Paltz",
    "State University of New York at Oneonta",
    "State University of New York at Oswego",
    "State University of New York at Purchase",
    "Sterling College",
    "Stetson University",
    "Stevens Institute of Technology",
    "Stony Brook University",
    "Suffolk University",
    "Swarthmore College",
    "Syracuse University",
    "Tarleton State University",
    "Taylor University",
    "Temple University",
    "Texas A&M University",
    "Texas A&M University-Kingsville",
    "The American College of Greece",
    "The College of Wooster",
    "The King's University",
    "The New School",
    "The Ohio State University at Lima",
    "The Ohio State University at Mansfield",
    "The Ohio State University at Marion",
    "The Ohio State University at Newark",
    "The Universidad Tecnologica Metropolitana",
    "The University of Adelaide",
    "The University of Georgia",
    "The University of Texas Rio Grande Valley",
    "Thompson Rivers University",
    "Towson University",
    "Transylvania University",
    "Trinity College",
    "Truman State University",
    "Tufts University",
    "Tulane University",
    "Unity College",
    "Universidad Autonoma de Tamaulipas",
    "Universidad Nacional Autonoma de Mexico",
    "Universidad San Francisco de Quito",
    "Universidad de Monterrey",
    "Universite Laval",
    "University at Albany",
    "University at Buffalo",
    "University for Peace",
    "University of Alaska Anchorage",
    "University of Alaska Fairbanks",
    "University of Alaska Southeast",
    "University of Alberta",
    "University of Amsterdam | Amsterdam University of Applied Sciences",
    "University of Arizona",
    "University of Arkansas",
    "University of Arkansas at Little Rock",
    "University of British Columbia",
    "University of Calgary",
    "University of California, Davis",
    "University of California, Irvine",
    "University of California, Los Angeles",
    "University of California, Merced",
    "University of California, Riverside",
    "University of California, San Diego",
    "University of California, Santa Barbara",
    "University of California, Santa Cruz",
    "University of Cincinnati",
    "University of Colorado Boulder",
    "University of Colorado Colorado Springs",
    "University of Colorado Denver - Anschutz Medical Campus",
    "University of Connecticut",
    "University of Dayton",
    "University of Denver",
    "University of Florida",
    "University of Greenwich",
    "University of Houston",
    "University of Illinois at Chicago",
    "University of Illinois, Urbana-Champaign",
    "University of Iowa",
    "University of Kansas",
    "University of Kentucky",
    "University of Louisville",
    "University of Maine",
    "University of Malaya",
    "University of Manitoba",
    "University of Maryland, College Park",
    "University of Massachusetts Amherst",
    "University of Massachusetts Dartmouth",
    "University of Massachusetts Lowell",
    "University of Massachusetts Medical School",
    "University of Memphis",
    "University of Michigan",
    "University of Michigan-Dearborn",
    "University of Minnesota, Duluth",
    "University of Minnesota, Morris",
    "University of Minnesota, Twin Cities",
    "University of Mississippi",
    "University of Missouri",
    "University of Missouri, Kansas City",
    "University of Missouri-St. Louis",
    "University of Montana",
    "University of Mount Union",
    "University of Nebraska - Lincoln",
    "University of Nebraska at Kearney",
    "University of Nebraska at Omaha",
    "University of Nevada, Las Vegas",
    "University of New Hampshire",
    "University of New Orleans",
    "University of North Carolina at Chapel Hill",
    "University of North Carolina, Charlotte",
    "University of North Carolina, Greensboro",
    "University of North Carolina, Wilmington",
    "University of North Florida",
    "University of North Texas",
    "University of Northern British Columbia",
    "University of Northern Iowa",
    "University of Notre Dame",
    "University of Oklahoma",
    "University of Ontario Institute of Technology",
    "University of Oregon",
    "University of Ottawa - Facilities",
    "University of Pennsylvania",
    "University of Puget Sound",
    "University of Redlands",
    "University of Richmond",
    "University of Rochester",
    "University of San Diego",
    "University of Saskatchewan",
    "University of South Carolina",
    "University of South Carolina Upstate",
    "University of South Florida",
    "University of Southern California",
    "University of Tennessee at Knoxville",
    "University of Texas at Arlington",
    "University of Texas at Austin",
    "University of Texas at El Paso",
    "University of Texas at San Antonio",
    "University of Twente",
    "University of Utah",
    "University of Vermont",
    "University of Victoria",
    "University of Virginia",
    "University of Washington, Seattle",
    "University of West Georgia",
    "University of Windsor",
    "University of Winnipeg",
    "University of Wisconsin-Green Bay",
    "University of Wisconsin-La Crosse",
    "University of Wisconsin-Milwaukee",
    "University of Wisconsin-Oshkosh",
    "University of Wisconsin-River Falls",
    "University of Wisconsin-Stevens Point",
    "University of Wisconsin-Stout",
    "University of Wisconsin-Whitewater",
    "University of the District of Columbia",
    "University of the Pacific",
    "University of the Sciences in Philadelphia",
    "Utah State University",
    "Utrecht University",
    "Valencia College",
    "Vassar College",
    "Vermont Technical College",
    "Villanova University",
    "Virginia Commonwealth University",
    "Virginia Tech",
    "Virginia Theological Seminary",
    "Wageningen University",
    "Wake Forest University",
    "Warren Wilson College",
    "Wartburg College",
    "Washington University in St. Louis",
    "Washington and Lee University",
    "Washtenaw Community College",
    "Weber State University",
    "Wellesley College",
    "Wesleyan University",
    "West Chester University of Pennsylvania",
    "Western Illinois University",
    "Western Kentucky University",
    "Western Michigan University",
    "Western Oregon University",
    "Western State Colorado University",
    "Western Technical College",
    "Western University",
    "Western Washington University",
    "Westminster College",
    "Whatcom Community College",
    "Whitman College",
    "Wilfrid Laurier University",
    "Williams College",
    "Worcester Polytechnic Institute",
    "Yale University",
    "Yeshiva University"):  # noqa

    PRELOADED_SUBSCRIPTION_NAMES.add(name)
