<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>STARS Tracking Tool<?php if(isset($this->title)) echo ' &middot; '.$this->title ?></title>
        <link href="/css/main.css" rel="stylesheet" type="text/css">
        <script src="/js/jquery.js" type="text/javascript"> </script>
        <script src="/js/main.js" type="text/javascript"> </script>
    </head>
    <body>
		<h1><a href="/">Sustainability Tracking and Ratings System</a></h1>

        <div id="login">
            <?php if(Zend_Auth::getInstance()->hasIdentity()) { ?>
                <p>
                    Logged in as 
                    <strong>
                        <?php echo STARS_Person::getInstance()->get('firstname').' '.STARS_Person::getInstance()->get('lastname') ?>
                    </strong>
                </p>
                <p>
                    <a href="/dashboard/">Dashboard</a>
                     / 
                    <a href="/user/logout/">Logout</a>
                </p>
            <?php } else { ?>
                <?php echo $this->loginForm ?>
            <?php } ?>
        </div>
        <div id="nav">
            <a href="../../tracking/STARS_Pilot_Phase_One_Guide.pdf">Pilot Phase 1 Guide (PDF)</a>

            <a href="../../tracking/faqs.php">STARS FAQ</a>
            <a href="http://www.aashe.org/stars/forum">Discussion Forum</a>
            <a href="mailto:stars@aashe.org?subject=STARS Question">Contact STARS Team</a>
            <a href="mailto:webmaster@aashe.org?subject=STARS Tracking Tool">Help?</a>
      </div>
      <div id="content">
         <?php echo $this->layout()->content ?>
     </div>
	</body>
</html>