<?php include('../application/views/scripts/header.phtml') ?>

<div id="title">
	TRUNK: STARS Tracking Tool
	<div id="breadcrumbs">Home</div>
</div>

<p>Welcome to the Sustainability Tracking, Assessment, and Rating System (STARS) Tracking Tool. STARS is a voluntary, self-reporting framework for gauging relative progress toward sustainability for colleges and universities.</p>

<p>The STARS Tracking Tool is available to <a href="http://www.aashe.org/stars/pilot_institutions.php">schools participating in the STARS Pilot Project</a>.  If you are working on the STARS Pilot Project and would like to enter data for your institution, please contact <a href="mailto:stars@aashe.org">stars@aashe.org</a> to request a user account. </p>  

<p>If you already have a STARS user account, <a href="/password/forgot/">click here to be reminded of your password</a>.</p>

<p class="starsbutton"><a href="/tracker">Enter STARS data</a></p>

    
<?php include('../application/views/scripts/footer.phtml') ?>