Vagrant::Config.run do |config|

    config.vm.define :web1 do |config|
        config.vm.box = "lucid32"
        config.vm.network('33.33.33.10')
        config.vm.customize do |vm|
            vm.memory_size = 256
        end
        config.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = "../chef/cookbooks"
            chef.roles_path = "../chef/roles"
            chef.add_role("web")
        end
    end
    
    config.vm.define :db1 do |config|
        config.vm.box = "lucid32"
        config.vm.network('33.33.33.20')
        config.vm.customize do |vm|
            vm.memory_size = 256
        end
        config.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = "../chef/cookbooks"
            chef.roles_path = "../chef/roles"
            chef.add_role("db")
        end
    end
    
end
