Vagrant::Config.run do |config|

    config.vm.define :web1 do |config|
      config.vm.box = "lucid32"
      config.vm.network('33.33.33.10')
      config.vm.customize do |vm|
          vm.memory_size = 256
      end
      config.vm.provision :chef_solo do |chef|
          chef.cookbooks_path = "../chef/cookbooks"
          chef.add_recipe("web")
      end
    end
    
    config.vm.define :db1 do |config|
      config.vm.box = "lucid32"
      config.vm.network('33.33.33.20')
      config.vm.customize do |vm|
          vm.memory_size = 256
      end
    end
    
end
