<h2><a href="/tracker/">My Tracker</a></h2>
<p>
    Edit your institutional, normalization, and credit information. 
</p>

<h2><a href="http://drupalsandbox.aashedev.org/user/<?php echo STARS_User::getId(); ?>/edit">Edit My Account</a></h2>
<p>
    Edit your E-mail address, password, and name.
</p>

<h2><a href="/user/logout/">Logout</a></h2>
<p>
    Logout from the STARS Tracking Tool. 
</p>