<div id="title">
    <?php echo $this->title ?>
    <div id="breadcrumbs">
        <a href="/">Home</a> / <a href="/dashboard/">Dashboard</a> / <?php echo $this->title ?>
    </div>
</div>

<table class="green">
	<tr>
    	<th>
        	Section Name
        </th>
<!--        <th>
        	Status
        </th>-->
    </tr>
    <tr>
    	<td>
	    	<a href="/institutional/">Institutional Info</a>
	    	<div class="help">Basic information about your institution</div>
        </td>
<!--        <td>

        	Incomplete
        </td>-->
    </tr>
    <tr>
    	<td>
	    	<a href="/normalization/">Annual Normalization Data</a>
	    	<div class="help">Additional information, changing year to year</div>
        </td>
<!--        <td>

        	Incomplete
        </td>-->
    </tr>
	<tr>
    	<td>
           	Education and Research
           	<div class="help">Not available in this release</div>
        </td>
<!--        <td>
        	Not Available
        </td>-->

    </tr>
    <tr>
    	<td>
	    	<a href="/section/2/">Operations</a>
	    	<div class="help">In development</div>
        </td>
<!--        <td>
        	Incomplete
        </td>-->
    </tr>

    <tr>
    	<td>
	    	<a href="/section/3/">Administration and Finance</a>
	    	<div class="help">In development</div>
        </td>
<!--        <td>
        	Incomplete
        </td>-->
    </tr>
</table>
