
<table class="green">
	<tr>
    	<th>
        	Section Name
        </th>
        <th>
        	Status
        </th>
        <th>
            Credit Forms (pilot project)
        </th>
    </tr>
    <tr>
    	<td>
	    	<span class='sectionTitle'><a href="/institutional/">Institutional Info</a></span>
	    	<div class="help">Basic information about your institution</div>
        </td>
        <td>
            &nbsp;<!-- no status -->
        </td>
        <td>
            &nbsp; <!-- no files -->
        </td>
    </tr>
    <tr>
    	<td>
	    	<span class='sectionTitle'><a href="/normalization/">Annual Normalization Data</a></span>
	    	<div class="help">Additional information, changing year to year</div>
        </td>
        <td>
            <?php if ($this->normInfo['isComplete']) : ?>
                <img src="/img/tick.png" alt="tick" title="Normalization Complete" border="0"/> 
            <?php endif ?>
            <?php echo $this->normInfo['msg']; ?>
            <div class="help">(<?php echo $this->normInfo['stats']; ?>)</div>
        </td>
        <td>
            &nbsp; <!-- no files -->
        </td>
    </tr>
    <?php foreach($this->section as $section) { ?>
      <tr>
        <td>
            <span class='sectionTitle'><a href=<?php echo $section->path; ?>>
               <?php echo $section->title; ?></a></span>
            <div class="help">Submit Credits for Pilot Project</div>
        </td>
        <td>
            <?php  if ($section->status['complete']) : ?>
               <img src="/img/tick.png" alt="tick" title="Section Complete" border="0"/>
            <?php  endif ?>
            <?php  echo $section->status['msg']; ?>
            <div class="help">(<?php echo $section->status['stats']; ?>)</div>

        </td>
        <td>
            <?php
              $forms = $section->forms;
              foreach($forms['filename'] as $filename) { ?>
                <a href="<?php echo $forms['linkPath'].$filename;?>"
                   title="Download Zip file">
                  <img src="/img/compress.png" alt="ZIP File" border=0/>
                  <?php echo $filename; ?></a><br>
            <?php }
              if ($forms['fileAvailable']) : ?>
                <div class="help">download <?php echo $section->title; ?> credit forms for pilot project </div>
            <?php endif ?>
        </td>
      </tr>
    <?php } // foreach section ?>
</table>
