
<table class="green">
	<tr>
    	<th>
        	Section Name
        </th>
        <th>
        	Status
        </th>
        <th>
            Credit Forms (pilot phase 1)
        </th>
    </tr>
    <tr>
    	<td>
	    	<a href="/institutional/">Institutional Info</a>
	    	<div class="help">Basic information about your institution</div>
        </td>
        <td>
            Ready<!-- 	Incomplete -->
        </td>
        <td>
            &nbsp; <!-- no files -->
        </td>
    </tr>
    <tr>
    	<td>
	    	<a href="/normalization/">Annual Normalization Data</a>
	    	<div class="help">Additional information, changing year to year</div>
        </td>
        <td>
            Ready<!-- 	Incomplete -->
        </td>
        <td>
            &nbsp; <!-- no files -->
        </td>
    </tr>
	<tr>
    	<td>
           	Education and Research
           	<div class="help">Not available until Phase 2</div>
        </td>
        <td>
            Not Available
        </td>
        <td>
            &nbsp; <!-- no files -->
        </td>

    </tr>
    <?php foreach($this->section as $section) { ?>
      <tr>
        <td>
            <a href=<?php echo $section->path; ?>>
               <?php echo $section->title; ?></a>
            <div class="help">Tier-1 Credits for Pilot Phase 1</div>
        </td>
        <td>
            Ready
<!--            <?php // if ($section->status['complete']) : ?>
               <img src="/img/tick.png" alt="tick" title="Section Complete" border="0"/>
            <?php // endif ?>
            <?php // echo $section->status['msg']; ?>
            <div class="help"><?php echo $section->status['stats']; ?></div>
-->
        </td>
        <td>
            <?php
              $forms = $section->forms;
              if ($forms['fileAvailable']) : ?>
                <a href="<?php echo $forms['fileLink'];?>"
                   title="Download Zip file">
                  <img src="/img/compress.png" alt="ZIP File" border=0/>
                  <?php echo $forms['filename']; ?></a>
                <div class="help">download all <?php echo $section->title; ?> credit forms for pilot phase 1 </div>
            <?php endif ?>
        </td>
      </tr>
    <?php } // foreach section ?>
</table>
