<div id="help">


<p>The step-by-step instructions below outline the process of submitting information for the STARS Pilot Project.  To be directed to a specific step in the process, click one of the links below.
</p>	

<ul>
<li><a href="#sign_in_and_enter_institutional_information">Sign In and Enter Institutional Information</a></li>
<li><a href="#enter_normalization_data">Enter Normalization Data</a></li>
<li><a href="#download_credit_forms">Download Credit Forms</a></li>
<li><a href="#enter_and_upload_credit_data">Enter and Upload Credit Data</a></li>
</ul>

<h2><a name="sign_in_and_enter_institutional_information"></a>Sign In and Enter Institutional Information</h2>

<ol>
<li>To login for the first time, you will need the password provided to you.  One login and password has been created for each institution.   If you do not have your password, please contact <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#116;&#97;&#114;&#115;&#64;&#97;&#97;&#115;&#104;&#101;&#46;&#111;&#114;&#103;">&#115;&#116;&#97;&#114;&#115;&#64;&#97;&#97;&#115;&#104;&#101;&#46;&#111;&#114;&#103;</a>.</li>
<li>Login via the box in the top right corner of the page:
<p><img src="/img/help_images/STARS-Help Guide-0.png"/></p> </li>
<li>After logging in, you will be redirected to your Dashboard. From the Dashboard, you will be able to enter basic institutional information, normalization data and download and upload PDF credit forms for the Operations and Administration and Finance sections. 
<p><img src="/img/help_images/STARS-Help Guide-1.png"/></p></li>
<li>Click on &#8220;Institutional Info&#8221; to get to the form where you can enter basic institutional information. The institutional information associated with your account will only need to be entered once and will not change. If you have a question about Carnegie Classification, click the "?" icon next to the Carnegie Question to reveal help text.
<p><img src="/img/help_images/STARS-Help Guide-2.png"/></p></li>
<li>When filling out the Institutional Information form, be sure to complete any field with &#8220;REQ&#8221; in red next to it. All of these fields are required.  </li>
<li>When you have completed the form, press the &#8220;Save Institution&#8221; button at the bottom of the page. 
</li>
</ol>
<h2><a name="enter_normalization_data"></a>Enter Normalization Data</h2>

<ol>
<li>After logging in, you will be redirected to My Tracker. </li>
<li>To start entering normalization data, which include population and building/space usage figures, select the "Annual Normalization Data"”" link from My Tracker. Normalization data are used in several credits that are normalized or adjusted according to population or building square footage. Since some STARS credits use data from three consecutive years, please enter normalization data for three years. </li>
<li>Before you can enter normalization data, you will need to create records for the years for which you will enter data. Create a normalization year by selecting a year in the drop-down menu and clicking &#8220;Create Year.&#8221;
<p><img src="/img/help_images/STARS-Help Guide-4.png"/></p></li>
<li>At this point, you can enter data for your newly created year or create more years.</li>
<li>To enter data for a specific year, click the Edit button in the Actions column. Enter all the data that you have at this time. It will be possible to go back and edit your normalization data later. 
	<p><img src="/img/help_images/STARS-Help Guide-5.png"/></p></li>
<li>After entering data on the edit form, select &#8220;Save normalization data&#8221; at the bottom of the form.
<!--<p><img src="/img/help_images/STARS-Help Guide-6.png"/></p>--> </li>
<li>To enter more normalization data, click on &#8220;Go back to Annual Normalization Data.&#8221;
<p><img src="/img/help_images/STARS-Help Guide-7.png"/></p> </li>
<li>You can view the status of your normalization data forms on the Annual Normalization Data page. When you have completed all of the required questions for a normalization year, your status will be marked as complete.
<p><img src="/img/help_images/STARS-Help Guide-8.png"/></p> </li>
<li>From the Annual Normalization Data page, you can enter normalization data for additional years following the steps outlined above. You should enter data for a minimum of 3 years. </li>
</ol>

<h2><a name="download_credit_forms"></a>Download Credit Forms</h2>

<ol>
<li>There is a separate PDF form for each credit.  You can download credit forms individually or you can download all forms bundled in two .zip files.  The credits are bundled in zip files by category (Operations and Administration and Finance). To download all the forms for a category, click the download link in the “Credit Forms (pilot phase 1)” column.
<p><img src="/img/help_images/STARS-Help Guide-9.png"/></p></li>
<li>To download an individual form, click the section name you want (such as "Operations"). On the Operations page, you should see a list of forms under the column &#8220;Get Credit Form.&#8221; Click on the form you want to download and save it to your desktop. 
<p><img src="/img/help_images/STARS-Help Guide-10.png"/></p></li>
</ol>

<h2><a name="enter_and_upload_credit_data"></a>Enter and Upload Credit Data</h2>

<ol>
<li>Open the PDF that you saved to your desktop with Adobe Reader 7 or higher. <strong>If you are using a Mac, you will need to use Acrobat Reader and not Preview.</strong> f you do not have Adobe Reader 7 or higher, you may download it for free at:
<a href="http://www.adobe.com/products/acrobat/readstep2.html"><a href="http://www.adobe.com/products/acrobat/readstep2.html">http://www.adobe.com/products/acrobat/readstep2.html</a> </li>
<li>After opening the PDF form, answer each question to the best of your abilities. Please note that you can copy and paste text from Word or Excel documents into PDF forms.</li>
<li>Remember to save the credit form after entering information! </li>
<!--<p><strong>Saving on a Mac:</strong></p>
<p><img src="/img/help_images/STARS-Help Guide-11.png"/></p>
<p><strong>Saving on a PC:</strong></p>
<p><img src="/img/help_images/STARS-Help Guide-12.png"/></p></li>-->
<li>To upload your completed credit form, click on the name of your credit in the "Submit Credit Data" column. For example, you could click on "Recycling Program" below.
<p><img src="/img/help_images/STARS-Help Guide-13.png"/></p> </li>

<li>Browse to the file you would like to upload and select it. Then, select "Browse" to upload your file. For each credit (though not the prerequisites, like Recycling Program), you will need to enter the estimated points your university would earn with the current version of the credit. Select "Upload" to upload the file and complete the submission for this credit. 
<p><img src="/img/help_images/STARS-Help Guide-14.png"/></p> </li>
<li>At any time, you can resubmit your file, download your file, or delete your file by clicking the name of the credit again in the &#8220;Submit Credit&#8221; column.  </li>
<li>Once you have submitted a file, the next time you click the name of the credit, you will see a new box named &#8220;Current Submission&#8221; at the top of your page. 
<p><img src="/img/help_images/STARS-Help Guide-15.png"/> </p></li>
<li>To upload additional forms, repeat the steps outlined above. </li>
</ol>

<p><strong>If you have additional questions that are not answered above, please email <a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#116;&#97;&#114;&#115;&#64;&#97;&#97;&#115;&#104;&#101;&#46;&#111;&#114;&#103;">&#115;&#116;&#97;&#114;&#115;&#64;&#97;&#97;&#115;&#104;&#101;&#46;&#111;&#114;&#103;</a> or post them to the <a href="http://www.aashe.org/stars/forum/">STARS Pilot Forum</a></strong>.</p>
</div>