from django.conf.urls.defaults import *

urlpatterns = patterns(
    'stars.apps.dashboard.credit_editor.views',
    
    (r'^$', 'home'),
    (r'^add-creditset/$', 'add_credit_set'),
    (r'^(?P<creditset_id>\d+)/$', 'credit_set_detail'),
    (r'^(?P<creditset_id>\d+)/add-category/$', 'add_category'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/$', 'category_detail'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/delete/$', 'delete_category'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/add-subcategory/$', 'add_subcategory'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/$', 'subcategory_detail'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/delete/$', 'delete_subcategory'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/add-credit/$', 'add_credit'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/$', 'credit_detail'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/delete/$', 'delete_credit'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/formula/$', 'credit_formula'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/formula/add-test/$', 'add_formula_test_case'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/formula/(?P<test_case_id>\d+)/$', 'formula_test_case'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/formula/(?P<test_case_id>\d+)/delete/$', 'delete_formula_test_case'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/add-field/$', 'add_field'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/fields/$', 'credit_fields'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/applicability/$', 'credit_applicability'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/applicability/(?P<reason_id>\d+)/$', 'edit_applicability'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/applicability/(?P<reason_id>\d+)/delete/$', 'delete_applicability'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/(?P<field_id>\d+)/$', 'field_detail'),
    (r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/(?P<field_id>\d+)/delete/$', 'delete_field'),
    #(r'^(?P<creditset_id>\d+)/(?P<category_id>\d+)/(?P<subcategory_id>\d+)/(?P<credit_id>\d+)/(?P<field_id>\d+)/delete-choice(?P<choice_id>\d+)/$', 'delete_choice'),
)