# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20181213_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Liaison Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='executive_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='president_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pendingaccount',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingaccount',
            name='user_level',
            field=models.CharField(choices=[(b'admin', b'Administrator'), (b'submit', b'Data Entry'), (b'view', b'Observer')], max_length=6, verbose_name=b'Role'),
        ),
        migrations.AlterField(
            model_name='registrationsurvey',
            name='reasons',
            field=models.ManyToManyField(blank=True, to='institutions.RegistrationReason'),
        ),
        migrations.AlterField(
            model_name='respondentsurvey',
            name='reasons',
            field=models.ManyToManyField(blank=True, to='institutions.RespondentRegistrationReason'),
        ),
        migrations.AlterField(
            model_name='starsaccount',
            name='user_level',
            field=models.CharField(choices=[(b'admin', b'Administrator'), (b'submit', b'Data Entry'), (b'view', b'Observer')], max_length=6, verbose_name=b'Role'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reason',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='confirmation',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='method',
            field=models.CharField(choices=[(b'credit', b'credit'), (b'check', b'check')], max_length=8),
        ),
    ]
