<p>Manually clear expired Log Entries: <a href='/watchdog/clearlog/'>Clear Log</a></p>
<table class='green'>
  <tr>
    <th>Type</th>
    <th>Severity</th>
    <th>Date</th>
    <th>Message</th>
  </tr>
<?php foreach($this->list as $entry) { ?>
  <tr>
    <td><?php echo $entry['type'] ?></td>
    <td><?php echo ($entry['severity']==WATCHDOG_ERROR?'Error':
                   ($entry['severity']==WATCHDOG_WARNING?'Warning':'Notice')) ?></td>
    <td><?php echo $entry['timestamp'] ?></td>
    <td><a href='/watchdog/entry/<?php echo $entry['watchdogid'] ?>'>
        <?php echo $entry['message'] ?> </a></td>
  </tr>
<?php } ?>
</table>