# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='access_to_institutions',
            field=models.ManyToManyField(blank=True, related_name='third_parties', to='institutions.Institution'),
        ),
    ]
