
<?php if (isset($this->report)): ?>
  <?php if (count($this->report->exportList)>0): ?>
    <div class= "messages" >
      The following <b><?php echo count($this->report->exportList); ?></b>
      normalization records were exported to <b><?php echo $this->report->filename; ?></b>
    </div>
    <ul>
       <?php foreach ($this->report->exportList as $norm) { ?>
         <li>
           <strong> <?php echo $norm ?> </strong>
         </li>
       <?php } ?>
    </ul>
  <?php endif; ?>

  <?php if (count($this->report->errorList)>0): ?>
    <div class= "errors" >
      ERROR: The following Normalization Data was NOT exported successfully:
    </div>
    <table>
       <?php foreach ($this->report->errorList as $norm => $errors) { ?>
         <tr>
            <td> <strong> <?php echo $norm; ?> </strong></td>
            <td> <?php foreach ($errors as $msg) echo $msg . '<br>'; ?> </td>
         </tr>
       <?php } ?>
    </table>
  <?php endif; ?>  
<?php endif; ?>

<?php if ($this->form): ?>
    <H2>!! ATTENTION !! </H2>
    <p><b>This is an administrative function used to export normalization data from the Database.</b></p>
    <p>
      <ul>
        <li>A CSV export file will be placed in the /files/exported_credit_data directory 
        <li>Each row will contain all normalization data for a single organization.
        <li>CSV file is named Normalization_export.csv .
      </ul>
    <H3>Please confirm you wish to continue with the Normalization Data Export:</H3>
    <?php echo $this->form ?>
    <p><strong>Please Note:</strong> 
    <ul>
    <li>Depending on how much data is in the database, this operation can be server intensive and time consuming - it is recommended that this operation be performed when the server load is expected to be light (e.g. on a holiday or late at night).
    </ul></p>
<?php endif; ?>
