<?php $credit = $this->credit;?>
<div id="title">
    <?php echo $this->title ?>
    <div id="breadcrumbs">
        <a href="/">Home</a> / <a href="/section/<?php echo $credit['dicreditcategory']; ?>"><?php echo $credit['sectiontitle'] .' Credits'; ?> </a> / Delete Credit
    </div>
</div>

<h2>'File Delete Failed'?>
</h2>
<h3><?php echo $credit['sectiontitle'] . ($credit['subsectiontitle']?(': ' . $credit['subsectiontitle']):''); ?> </h3>
<h3><?php echo $credit['title']; ?></h3>

  <div class='file-error'>
    <p>An error occurred - 
       <a href='/credit/upload/?credit=<?php echo $credit['creditid']; ?> '>please try again</a>.
    </p>
    <h2>File was NOT deleted!</h2>
  </div>
