<?php $credit = $this->credit;?>
<div id="title">
    <?php echo $this->title ?>
    <div id="breadcrumbs">
        <a href="/">Home</a> / <a href="/section/<?php echo $credit['dicreditcategory']; ?>"><?php echo $credit['sectiontitle'] .' Credits'; ?> </a> / Submit Credit
    </div>
</div>

<!--<h2><?php echo $credit['sectiontitle'] . ($credit['subsectiontitle']?(': ' . $credit['subsectiontitle']):''); ?> </h2>
<h3><?php echo $credit['title']; ?> </h3>-->

<?php if ($this->fileOptions) : ?>
    <div class="green">
        <h3>Current Submission</h3>
        <p style="text-align: center">
            <span style="margin: auto 2em">
              <img src="/img/page_white_acrobat.png" alt="PDF File" title="Your Submission for this credit" border=0/> <strong><?php echo $this->fileOptions['filename']; ?></strong>
            </span>            
            <span style="margin: auto 2em">
                <a href="<?php echo $this->fileOptions['saveURL'];?>"> <img src="/img/disk.png" alt="Save File" title="Click to Download your Submission" border=0/></a> <a href="<?php echo $this->fileOptions['saveURL'];?>">Download this File</a>
            </span>
            <span style="margin: auto 2em">
                <a href="<?php echo $this->fileOptions['deleteURL'];?>"> <img src="/img/cross.png" alt="Delete File" title="Click to Delete this Submission" border=0/></a> <a href="<?php echo $this->fileOptions['deleteURL'];?>">Delete this File</a>
            </span>
        </p>
        <p>To edit your submission, simply download the file, edit it, and re-submit it below.</p>
    </div>
<?php endif ?>

<?php if ($this->error): ?>
  <div class="errors">
    No credit data was submitted. Please correct any errors below and try again.
  </div>
<?php endif ?>

<?php echo $this->form ;?>
