<?php include('../application/views/scripts/header.phtml') ?>

            <div id="title">
               Error
                <div id="breadcrumbs"><a href="/">Home</a> / Error</div>
            </div>
            
            <div class="errors">
                <?php echo $this->errors->exception->getMessage() ?>
            </div>
            
<?php include('../application/views/scripts/footer.phtml') ?>