
<h2>The STARS Tracking Tool is Offline for site Maintenance</h2>

<h3>We expect the site to be available again by Aug. 8, 2008 - please check back then. </h3>

<p>STARS is a voluntary, self-reporting framework for gauging relative progress toward sustainability for colleges and universities.</p>

<p>If you would like more infomrmation about STARS, or have questions about its availability, please contact <a href="mailto:stars@aashe.org">stars@aashe.org</a>. </p>  

