<?php include('../application/views/scripts/header.phtml') ?>

<div id="title">
	Reset Password
	<div id="breadcrumbs"><a href="/">Home</a> / Reset Password</div>
</div>

<?php if($this->noKey) { ?>
    <div class="errors">
        You need a reset key to reset your password. To get one, <a href="/password/forgot/">click here</a>.
    </div>
<?php } ?>

<?php if($this->attempted) { ?>
    <?php if($this->code == STARS_PasswordResetter::SUCCESS) { ?>
        <p>
            Your password has been reset. You may log in with your new password now.
        </p>
    <?php } elseif($this->code == STARS_PasswordResetter::KEY_ERROR) { ?>
        <div class="errors">
            The key you provided is expired or otherwise invalid.
        </div>

        <?php echo $this->form ?>
    <?php } else { ?>
        <p>
            There was an error processing your data. Please contact the <a href="mailto:webmaster@aashe.org?subject=STARS Tracking Tool">IT Team</a> with a detailed description of the problem you encountered..
        </p>
    <?php } ?>
<?php } else { ?>
    <?php echo $this->form ?>
<?php } ?>

<?php include('../application/views/scripts/footer.phtml') ?>