
<?php if($this->attempted) { ?>
    <?php if($this->code == STARS_UserInserter::SUCCESS) { ?>
        <p>
            The user has been created successfully.
        </p>
            <ul>
                <li><a href="/dashboard/">Return to dashboard.</a></li>
                <li><a href="/">Go home.</a></li>
            </ul>
    <?php } elseif($this->code == STARS_UserInserter::USERNAME_ERROR) { ?>
            <ul class="errors">
                <li>That username already exists.</li>
            </ul>
        <?php echo $this->form ?>
    <?php } else { ?>
        <p>
            There was an error processing your data. Please contact the <a href="mailto:webmaster@aashe.org?subject=STARS Tracking Tool">IT Team</a> with a detailed description of the problem you encountered..
        </p>
    <?php } ?>
<?php } else { ?>
    <?php if($this->submitted) { ?>
        <div class="errors">
            The errors in your submission have been highlighted below.
        </div>
    <?php } ?>
    <?php echo $this->form ?>
<?php } ?>
