<?php if ($this->message): ?>
  <div class="messages">
    <?php echo $this->message; ?>
  </div>
<?php endif; ?>

<?php if($this->submitted) { ?>
        <div class="errors">
            The errors in your submission have been highlighted below.
        </div>
<?php } ?>
<h2><?php echo $this->user['name'] ?></h2>
    <ul>
        <li>
            User Level: <?php echo $this->user['roles'] ?>
        </li>
        <li>
            e-mail: <?php echo $this->user['mail'] ?>
        </li>
    </ul>

<table width=80% align='center'>
  <thead> <tr>
    <th>Organization</th> <th>Role</th> <th>Title</th> <th>Department</th> <th>Admin Action</th>
  </tr></thead>
<?php foreach($this->userOrgs as $org) { ?>
  <tr>
	<td><?php echo $org['orgname'] ?></td>
    <td><?php echo $org['role'] ?></td>
    <td><?php echo $org['title'] ?></td>
    <td><?php echo $org['department'] ?></td>
    <td> <a href="/user/deleteorgrole/<?php echo $org['relperson2orgid'] ?>/">Delete</a></td>
  </tr>
<?php } ?>
</table>
<?php echo $this->form ?>
