<?php include('../application/views/scripts/header.phtml') ?>

<div id="title">
	Edit Profile
	<div id="breadcrumbs"><a href="/">Home</a> / <a href="/dashboard/">Dashboard</a> / Edit Profile</div>
</div>

<?php if($this->attempted) { ?>
    <?php if($this->code == STARS_UserUpdater::SUCCESS) { ?>
        <p>
            Profile updated.
        </p>
        <p>
            <ul>
                <li><a href="/">Go home.</a></li>
                <li><a href="/tracker/">Go to My Tracker.</a></li>
            </ul>
        </p>
    <?php } elseif($this->code == STARS_UserUpdater::NO_UPDATE_ERROR) { ?>
        <div class="errors">
            No changes have been made Either you did not enter changes, or the user does not exist.
        </div>
        <?php echo $this->form ?>
    <?php } else { ?>
        <p>
            There was an error processing your data. Please contact the <a href="mailto:webmaster@aashe.org?subject=STARS Tracking Tool">IT Team</a> with a detailed description of the problem you encountered.. Please contact the webmaster if you continue to have problems.
        </p>
    <?php } ?>
<?php } else { ?>
    <?php if($this->submitted) { ?>
        <div class="errors">
            The errors in your submission have been highlighted below.
        </div>
    <?php } ?>
    <?php echo $this->form ?>
<?php } ?>

<?php include('../application/views/scripts/footer.phtml') ?>