
<?php foreach($this->list as $user) { ?>
    <h2><?php echo $user['name'] ?></h2>
    <ul>
        <li>
            User Level: <?php echo $user['role'] ?>
        </li>
        <li>
            e-mail: <?php echo $user['mail'] ?>
        </li>
        <li>
            <?php if ($user['personid']===NULL) { ?>
            	<b>NO ORGANIZATION ASSIGNED</b>
            <?php } else { ?>
            	Organization: <?php echo $user['orgname'] . '   ('. $user['orgrole'] . ')' ?>
            <?php } ?>
        </li>
        <li>
            Administrative Actions:
            <a href="/user/edit/<?php echo $user['userid'] ?>/">Edit</a>
        </li>
    </ul>
<?php } ?>
