<?php include('../application/views/scripts/header.phtml') ?>

<div id="title">
	User Administration
	<div id="breadcrumbs"><a href="/">Home</a> / <a href="/dashboard/">Dashboard</a> / User Administration</div>
</div>

<?php foreach($this->list as $user) { ?>
    <h2><?php echo $user['username'] ?></h2>
    <ul>
        <li>
            User Level: <?php echo ($user['level'] == 2) ? 'Administrator' : 'Normal User' ?>
        </li>
        <li>
            Real Name: <?php echo $user['firstname'].' '.$user['lastname'] ?>
        </li>
        <li>
            Organization: <?php echo $user['orgname'] ?>
        </li>
        <li>
            Administrative Actions:
            <a href="/user/edit/<?php echo $user['personid'] ?>/">Edit</a>,
            <a href="/user/delete/<?php echo $user['personid'] ?>/" onclick="return confirm('Are you sure you want to delete <?php echo str_replace(array('\'', '"'), array('\\\'', '\\\''), $user['firstname'].' '.$user['lastname']) ?>\'s account?')">Delete</a>
        </li>
    </ul>
<?php } ?>

<?php include('../application/views/scripts/footer.phtml') ?>