<?php if($this->attempted) { ?>
    <?php if(!$this->success) { ?>
        <p>
          <?php echo $this->message; ?>
        </p>
    <?php } else { // This should NEVER happen! ?>
        <p>
            You've successfully logged in.
        </p>
        <p>
            <a href="/tracker/">Go to My Tracker.</a>
        </p>
    <?php } ?>
<?php } else { ?>
    <div class="errors">
       <p>You must enter a username and password above.</p>
    </div>
<?php } ?>
