
<?php if($this->already) { ?>
    <p>
        You're already logged in.
    </p>
    <p>
        <a href="/tracker/">Go to My Tracker.</a>
    </p>
<?php } else { ?>
    <?php if($this->attempted) { ?>
        <?php if(!$this->success) { ?>
            <p>
              <?php echo $this->message; ?>
            </p>
        <?php } else { ?>
            <p>
                You've successfully logged in.
            </p>
            <p>
                <a href="/tracker/">Go to My Tracker.</a>
            </p>
        <?php } ?>
    <?php } else { ?>
        <p>
            You must enter a username and password above.
        </p>
    <?php } ?>
<?php } ?>
