<div id="title">
    <?php echo $this->title ?> Credit Forms (downloads)
    <div id="breadcrumbs">
        <a href="/">Home</a> / <a href="/tracker/">My Tracker</a> / <?php echo $this->title ?>
    </div>
</div>

<?php if ($this->message): ?>
  <div class="messages">
    <?php echo $this->message; ?>
  </div>
<?php endif; ?>

<table class="green">
	<tr>
    	<th>
        	Credit Number
        </th>
        <th>
        	Credit Name
        </th>
        <th>
        	Form
        </th>
        <th>
        	Status
        </th>
    </tr>
    <?php $prevtitle = '' /* Prerequisite section name is '' */ ?>
    <?php foreach($this->credits as $credit) { ?>
        <?php if($prevtitle != $credit['subsectiontitle']) { ?>
            <tr>
                <th colspan="4">
                    <?php echo $prevtitle = $credit['subsectiontitle'] ?>
                </th>
            </tr>
        <?php } ?>
        <tr>
            <td>
                <?php echo $credit['sectionabbr'] ?>
                <?php echo ($credit['prerequisite'] == 1) ? 'Prereq' : 'Credit' ?>
                <?php echo $credit['creditnumber'] ?>
            </td>
            <td>
                <?php echo $credit['creditname'] ?>
            </td>
            <td>
              <?php if (key_exists('downloadAvailable', $credit)): ?>
                <a href="<?php echo $credit['filepath'] ?>">
                         <img src="/img/page_white_acrobat.png" 
                              alt="PDF File" 
                              title="Click to download form" border=0/>
                         <?php echo $credit['filename'] ?> </a>
              <?php else: ?>
                 not available
              <?php endif ?>
             </td>
            <td align="center">
                <?php echo empty($credit['status']) ? ' - ' : '<img src="/img/tick.png" alt="tick" title="Credit Submitted">' ?>
            </td>
        </tr>
    <?php } ?>
</table>
