<div id="title">
    <?php echo $this->title ?>
    <div id="breadcrumbs">
        <a href="/">Home</a> / <a href="/tracker/">My Tracker</a> / <?php echo $this->title ?>
    </div>
</div>

<?php if ($this->message): ?>
  <div class="messages">
    <?php echo $this->message; ?>
  </div>
<?php endif; ?>

<table class="green">
	<tr>
    	<th>
        	Credit Number
        </th>
        <th>
        	Credit Name
        </th>
        <th>
        	Status
        </th>
        <th>
        	Submission
        </th>
        <th>
        	Updated
        </th>
    </tr>
    <?php $prevtitle = '' /* Prerequisite section name is '' */ ?>
    <?php foreach($this->credits as $credit) { ?>
        <?php if($prevtitle != $credit['subsectiontitle']) { ?>
            <tr>
                <th colspan="5">
                    <?php echo $prevtitle = $credit['subsectiontitle'] ?>
                </th>
            </tr>
        <?php } ?>
        <tr>
            <td>
                <?php echo $credit['sectionabbr'] ?>
                <?php echo ($credit['prerequisite'] == 1) ? 'Prereq' : 'Credit' ?>
                <?php echo $credit['creditnumber'] ?>
            </td>
            <td>
                <a href="/credit/upload/<?php echo $credit['creditid'] ?>/"><?php echo $credit['creditname'] ?></a>
            </td>
            <td align="center">
                <?php echo empty($credit['status']) ? ' - ' : '<img src="/img/tick.png" alt="tick" title="Credit Uploaded">' ?>
            </td>
            <td>
                <?php  
                // This is So WRONG & duplicate code - model needs to be re-factored?
                // Lots of opportunity for poor error handling here - sure to break.
                if (empty($credit['status']))
                { echo ' '; }
                else {
                  $file = new STARS_CreditPdfFile($credit['orgcreditfileid']);
                  //$fileoptions = CreditFileActionHelper::_getFileOptions($file);
                  $filename = $file->getDisplayName();
                  $viewURL  = '/credit/viewfile/' . $credit['creditid'];
                  echo '<a href="' . $viewURL .'"> <img src="/img/page_white_acrobat.png" alt="PDF File" title="Click to View your Submission" border=0/></a> <a href="'
                   . $viewURL .'">'
                   . $filename .'</a>';
                } ?>
             </td>
            <td>
                <?php echo empty($credit['status']) ? '': $credit['datemodified'] ?>
            </td>
        </tr>
    <?php } ?>
</table>
