<table class="green">
	<tr>
    	<th>
        	Get Credit Form
        </th>
        <th>
        	Submit Credit Data
        </th>
        <th colspan="2">
        	Status
        </th>
        <th>
        	Updated
        </th>
    </tr>
    <?php $prevtitle = '' /* Prerequisite section name is '' */ ?>
    <?php foreach($this->credits as $credit) { ?>
        <?php if($prevtitle != $credit['subsectiontitle']) { ?>
            <tr>
                <th colspan="5">
                    <?php echo $prevtitle = $credit['subsectiontitle'] ?>
                </th>
            </tr>
        <?php } ?>
        <tr>
            <td>
              <?php if ($credit['form']['available']): ?>
                <a href="<?php echo $credit['form']['link'] ?>"
                   title="Click to download form">
                    <img src="/img/page_white_acrobat.png" 
                         alt="PDF File" 
                         border=0/>
                    <?php echo $credit['form']['filename'] ?> </a>
              <?php else:
                  echo $credit['submit']['creditCode'];
                endif;
              ?>
            </td>
            <td>
              <a href= "<?php echo $credit['submit']['uploadLink'] ?>/"
                 title="<?php echo $credit['submit']['uploadTitle'] ?>" >
                <?php echo $credit['creditname'] ?></a>
            </td>
            <?php if ($credit['submission']['available']): ?>
              <td align="center">
                <img src="/img/tick.png" alt="tick" title="Credit Uploaded" />
              </td>
              <td>
                <a href="<?php echo $credit['submission']['link']; ?>" title="Click to Download your Submission"> <img src="/img/disk.png" alt="PDF File" border=0/>
                 <?php echo $credit['submission']['filename']; ?> </a>
              </td>
              <td>
                <?php echo $credit['datemodified']; ?>
              </td>
            <?php else: ?>
              <td align="center"> - </td>
              <td> &nbsp; </td>
              <td> &nbsp; </td>
            <?php endif ?>
        </tr>
    <?php } ?>
</table>
