<div id="title">
    <?php echo $this->title ?>
    <div id="breadcrumbs">
      <?php echo $this->breadcrumb()->render(); ?>
    </div>
</div>

<?php if ($this->message): ?>
  <div class="messages">
    <?php echo $this->message; ?>
  </div>
<?php endif; ?>

Analyzed all PDF Forms in <?php echo $this->formsDir; ?> to verify:
<ul>
  <li>Each Credit in DB has a matching form file;
  <li>Each Form has a matching Credit in DB;
  <li>Each Form contains valid Meta-data, used to validate submissions.
<ul> 
<table class = "green">
  <tr>
    <td>Credits in DB</td>
    <td><?php echo $this->numCredits; ?></td>
  </tr>
  <tr>
    <td>Forms in <?php echo $this->formsDir; ?> directory</td>
    <td><?php echo $this->numForms; ?></td>
  </tr>
  <tr>
    <td>Number of Tests that FAILED</td>
    <td><?php echo count($this->msgs); ?></td>
  </tr>
</table>
<h3>Detectd <?php echo count($this->msgs); ?> possible problems</h3>
<table class="green">
	<tr>
    	<th>
        	Credit Form
        </th>
        <th>
        	Error condition detected
        </th>
    </tr>
    <?php foreach($this->msgs as $form => $msg) { ?>
      <tr>
        <td><?php echo $form; ?></td>
        <td><?php echo $msg; ?></td>
      </tr>
    <?php } ?>
</table>
